/* CHAR FUNCTION
    UPPER LOWER INITCAP
*/
SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;

SELECT * FROM EMP WHERE LOWER(ENAME)='james';
--LENGTHB 는 바이트의 길이 값을 반환함.
SELECT ENAME, LENGTH(ENAME), SAL,LENGTH(SAL),LENGTH('한글'),LENGTHB('한글')
FROM EMP;