/*CREATE TABLE TABLE_NAME(
        COLUMN_NAME DATA_TYPE(LENGTH)
*/
DROP TABLE EMP_DDL;
CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7),
    COMM NUMBER(7),
    DEPINO NUMBER(2)
    );
    
DESC EMP_DDL;

CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;

CREATE TABLE SALGRADE_DDL
AS SELECT * FROM SALGRADE;

/*ALTER TABLE TABLE_NAME
  1.ADD <COLNAME> <DATATYPE>; //추가
  2.DROP <COLNAME>; //삭제
  3.MODIFY <COLNAME> <DATATYPE>; //수정
  4.RENAME COLUMN <OLD_COLNAME> TO <NEW_COLNAME>
 */
 
ALTER TABLE SALGRADE_DDL
ADD PARTY VARCHAR2(20);

ALTER TABLE SALGRADE_DDL
RENAME COLUMN PARTY TO HOME;

ALTER TABLE SALGRADE_DDL
DROP COLUMN HOME;

RENAME SALGRADE_DDL TO SALZIP;

DESC SALZIP;
SELECT * FROM SALZIP;

TRUNCATE TABLE SALZIP;
DROP TABLE SALZIP;
/*
COMMENT ON TABLE <TABLE_NAME> IS <COMMENT>;
COMMENT ON COLUMN <TABLE_NAME>.<COLNAME> IS <COMMENT>;
*/
COMMENT ON TABLE DEPT_DDL IS 'DDL연습테이블';

COMMENT ON COLUMN DEPT_DDL.LOC IS '부서 위치';

CREATE TABLE PERSONS(
    ID VARCHAR2(4) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL UNIQUE,
    AGE NUMBER(3) CHECK(AGE>=18),
    TELNUM VARCHAR2(20),
    ADDR VARCHAR2(100) DEFAULT 'SEOUL',
    BDAY DATE DEFAULT SYSDATE
    );
INSERT INTO PERSONS(ID,NAME,AGE,TELNUM)
VALUES('1001','SCOTT',20,'01012344567');

INSERT INTO PERSONS(NAME,AGE,TELNUM)
VALUES('SCOTT',20,'01012344567');

CREATE TABLE PERSONS2(
    ID VARCHAR2(4),
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER(3),
    TELNUM VARCHAR2(20),
    ADDR VARCHAR2(100) DEFAULT 'SEOUL',
    BDAY DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PERSON2 PRIMARY KEY(ID),
    CONSTRAINT UN_PERSON2 UNIQUE(NAME),
    CONSTRAINT CHR_PERSON2 CHECK(AGE>=18)
    );

ALTER TABLE PERSONS2 MODIFY ADDR DEFAULT 'PARIS';

ALTER TABLE PERSONS2 DROP CONSTRAINT CHR_PERSON2;

ALTER TABLE PERSONS2 ADD CONSTRAINT CHK_P2 CHECK(AGE>50);

CREATE TABLE PLAYS(
    PLAY_ID NUMBER(10) PRIMARY KEY,
    PLAY_RESULT VARCHAR2(100),
    PERSONS_ID VARCHAR2(4),
    CONSTRAINT FK_PLAYS FOREIGN KEY(PERSONS_ID)
    REFERENCES PERSONS(ID) ON DELETE CASCADE
);
-- ON DELETE SET NULL
CREATE TABLE PKTABLE(
    PKVAL VARCHAR2(10),
    CONSTRAINT PK_KEY PRIMARY KEY (PKVAL)
);
CREATE TABLE FKTABLE(
    PKVAL VARCHAR2(10),
    FKVAL VARCHAR2(10)
);
ALTER TABLE FKTABLE ADD CONSTRAINT FK_KEY
FOREIGN KEY(FKVAL) REFERENCES PKTABLE(PKVAL) ON DELETE CASCADE ;

ALTER TABLE FKTABLE ADD CONSTRAINT FKT_PK_KEY PRIMARY KEY(PKVAL);

INSERT INTO PKTABLE VALUES('PK1');
INSERT INTO PKTABLE VALUES('PK2');
INSERT INTO PKTABLE VALUES('PK3');
SELECT * FROM PKTABLE;
INSERT INTO FKTABLE VALUES('PK1-VAL1','PK1');
INSERT INTO FKTABLE VALUES('PK1-VAL2','PK1');
INSERT INTO FKTABLE VALUES('PK2-VAL1','PK2');
INSERT INTO FKTABLE VALUES('PK2-VAL2','PK2');
INSERT INTO FKTABLE VALUES('PK3-VAL1','PK3');
INSERT INTO FKTABLE VALUES('PK3-VAL2','PK3');

DELETE FROM PKTABLE WHERE PKVAL='PK1';
SELECT * FROM PKTABLE;
SELECT * FROM FKTABLE;
--Q1 EMP_HW TABLE 생성 제약조건 참조
CREATE TABLE EMP_HW(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7),
    COMM NUMBER(7),
    DEPTNO NUMBER(2)
);
